source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DRNetworkUpdatingPlist_Example', :exclusive => true do
  pod 'DRNetworkUpdatingPlist', :path => '../'
end

target 'DRNetworkUpdatingPlist_Tests', :exclusive => true do
  pod 'DRNetworkUpdatingPlist', :path => '../'

  
end
